//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigMill.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PollAnswer> PollAnswers { get; set; }
        public virtual DbSet<PollLog> PollLogs { get; set; }
        public virtual DbSet<PollQuestion> PollQuestions { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostsCategory> PostsCategories { get; set; }
        public virtual DbSet<PostsComment> PostsComments { get; set; }
        public virtual DbSet<PostsCommentsReply> PostsCommentsReplies { get; set; }
        public virtual DbSet<PostsSubCategory> PostsSubCategories { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketInbox> TicketInboxes { get; set; }
        public virtual DbSet<TicketInboxMedia> TicketInboxMedias { get; set; }
        public virtual DbSet<TicketLog> TicketLogs { get; set; }
        public virtual DbSet<TicketOutbox> TicketOutboxes { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<Tags_Posts_Mapping> Tags_Posts_Mapping { get; set; }
        public virtual DbSet<Tags_PostsCategory_Mapping> Tags_PostsCategory_Mapping { get; set; }
        public virtual DbSet<Tags_PostsSubCategory_Mapping> Tags_PostsSubCategory_Mapping { get; set; }
    }
}
